name: CVE Check
on:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Linux
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.x
      - name: Restore
        id: restore
        run:  echo "CVECOUNT=$(dotnet restore -v m | grep -c -e 'NU190[1-4]')" >> "$GITHUB_OUTPUT"
      - name: List vulnerabilities
        if: steps.restore.outputs.CVECOUNT > 0
        run: dotnet list package --vulnerable --include-transitive --format json >> "${{ github.workspace }}/vulnerabilities.json"
      - name: Archive vulnerability report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerabilities
          path: ${{ github.workspace }}/vulnerabilities.json