name: NuGet Audit
on:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  call-nuget-audit:
    uses: particular/shared-workflows/.github/workflows/audit-nuget.yml@main
    secrets: inherit
  report-results:
    runs-on: ubuntu-22.04
    needs: call-nuget-audit
    if: always()
    steps:
      - run: |
          echo "### dotnet restore result" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "```bash" >> $GITHUB_STEP_SUMMARY
          echo ${{ needs.call-nuget-audit.outputs.dotnetrestore }} >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
