name: NuGet Audit
on:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  call-nuget-audit:
    uses: particular/shared-workflows/.github/workflows/audit-nuget.yml@main
    secrets: inherit
  report-results:
    runs-on: ubuntu-22.04
    needs: call-nuget-audit
    if: always()
    steps:
      - run: |
          {
            echo "### `dotnet restore` result"
            echo ""
            while read p; do
              echo "$p"
            done <${{ github.workspace }}/results/dotnetrestore.log
          } > $GITHUB_STEP_SUMMARY
