name: Deploy Staging
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
jobs:
  check-authorized-user:
    uses: ./.github/workflows/check-authorized-user.yml
  push-nuget-packages-staging:
    needs: check-authorized-user
    permissions:
      id-token: write
      contents: write
    uses: ./.github/workflows/push-nuget-packages-staging.yml
    with:
      version: ${{ inputs.version }}
      exclude-package-pattern: "TotallyLegit.ServiceControl.Management.*.nupkg"
    secrets: inherit
  generate-release-notes:
    needs: check-authorized-user
    uses: ./.github/workflows/generate-release-notes.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit
