name: Release - build and store artifacts
on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  build-and-store-artifacts:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6.0.0
        with:
          dotnet-version: 10.0.x
          # source-url: ${{ vars.FEED_URL}}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.FEED_TOKEN}}
      - name: Setup GitReleaseManager
        # https://github.com/GitTools/GitReleaseManager#net-global-tool
        run: dotnet tool install --global GitReleaseManager.Tool
      - name: Build
        run: dotnet build src --configuration Release
      - name: Build example console app to mimic ServiceControl exe output
        run: dotnet build src/TotallyLegit.App --configuration Release -p:WindowsSelfContained=true
      - name: Sign NuGet packages
        uses: Particular/sign-nuget-packages-action@v1.0.0
        with:
         client-id: ${{ secrets.AZURE_KEY_VAULT_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_KEY_VAULT_TENANT_ID }}
         client-secret: ${{ secrets.AZURE_KEY_VAULT_CLIENT_SECRET }}
         certificate-name: ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE_NAME }}
      - name: Update PowerShell module version
        # SHOULD NOT BE PART OF REAL RELEASES
        # This is only here to make testing easier since we are packaging the same folder over and over.
        # It keeps the published module version in sync with the release tag so we don't have to keep deleting the same version from feedz.
        run: |
          Update-PSModuleManifest -Path TotallyLegit.ServiceControl.Management/TotallyLegit.ServiceControl.Management.psd1 -ModuleVersion "${{ github.ref_name }}"
      - name: Compress PowerShell Module
        run: |
          New-Item -ItemType Directory -Path powershellModules -Force
          Compress-PSResource -Path TotallyLegit.ServiceControl.Management -DestinationPath powershellModules
      - name: Publish NuGet packages to the workflow
        uses: actions/upload-artifact@v7.0.1
        with:
          name: nugets
          path: nugets/*
          retention-days: 1
      - name: Publish Powershell modules to the workflow
        uses: actions/upload-artifact@v7.0.1
        with:
          name: powershell
          path: powershellModules/*
          retention-days: 1
      - name: Publish assets
        uses: actions/upload-artifact@v7.0.1
        with:
          name: assets
          path: assets/*
          retention-days: 1
      - name: Create draft release and attach assets
        run: |
          Write-Output "Creating draft release for ${{ github.event.repository.name }} ${{ github.ref_name }} at commit ${{ github.sha }}"
          "--RELEASE PENDING--" | Set-Content -Path release-body.md -NoNewline
          $assets = (Get-ChildItem -Path nugets/, powershellModules/, assets/ -File).FullName -join ","
          Write-Output "Attaching assets: $assets"
          dotnet-gitreleasemanager create --token $env:GITHUB_TOKEN -o "${{ github.repository_owner }}" -r "${{ github.event.repository.name }}" -n "${{ github.ref_name }}" -c "${{ github.sha }}" -i release-body.md -a $assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

