name: Deploy Production
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
jobs:
  check-authorized-user:
    uses: ./.github/workflows/check-authorized-user.yml
  publish-release-notes:
    needs: check-authorized-user
    uses: ./.github/workflows/publish-release-notes.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit
  virus-scan:
    needs: publish-release-notes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Scan release for viruses
        uses: Particular/virus-scan-action@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          tag: ${{ inputs.version }}
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: ${{ vars.VIRUS_REPORTING_SLACK_CHANNEL }}
  push-nuget-packages:
    permissions:
      id-token: write
    needs: publish-release-notes
    uses: ./.github/workflows/push-nuget-packages.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit
  push-docker-images:
    needs: publish-release-notes
    uses: ./.github/workflows/push-docker-images.yml
  push-powershell-packages:
    needs: publish-release-notes
    uses: ./.github/workflows/push-powershell-packages.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit
  push-release-info-to-aws-s3:
    needs: publish-release-notes
    uses: ./.github/workflows/push-release-info-to-aws-s3.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit
