name: Deploy Staging
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
jobs:
  check-authorized-user:
    uses: Particular/deployment-workflows/.github/workflows/authorize-user.yml@0.0.1
  push-nuget-packages-staging:
    needs: check-authorized-user
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Push NuGet packages
        uses: Particular/deployment-workflows/.github/actions/push-nuget-packages@combine-push-nuget-package-steps
        with:
          version: ${{ inputs.version }}
          exclude-package-pattern: "TotallyLegit.ServiceControl.Management.*.nupkg"
          publish-mode: api-key
          feed-url: ${{ vars.PARTICULAR_TESTING_FEED_URL }}
          api-key: ${{ secrets.FEEDZIO_PUBLISH_API_KEY }}
  generate-release-notes:
    needs: check-authorized-user
    uses: Particular/deployment-workflows/.github/workflows/generate-release-notes.yml@0.0.1
    with:
      version: ${{ inputs.version }}
    secrets: inherit
